name: rms-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - flask
  - flask-mail
  - flask-sqlalchemy
  - flask-migrate
  - sqlalchemy
  - itsdangerous
  - werkzeug
  - jinja2
  - pytest
  - flake8
  - pip:
      - python-dotenv
