"""Initial migration

Revision ID: 80c9598a27b5
Revises: 
Create Date: 2024-12-01 11:37:06.743216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c9598a27b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('report_details', sa.String(length=500), nullable=False),
    sa.Column('anonymous_contact', sa.String(length=100), nullable=True),
    sa.Column('access_code', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('harassment_details', sa.String(length=1000), nullable=True),
    sa.Column('harassment_type', sa.String(length=100), nullable=True),
    sa.Column('harassment_frequent', sa.String(length=100), nullable=True),
    sa.Column('harassment_witnesses', sa.String(length=255), nullable=True),
    sa.Column('harassment_previous_reports', sa.String(length=100), nullable=True),
    sa.Column('harassment_reporting_person', sa.String(length=255), nullable=True),
    sa.Column('harassment_response', sa.String(length=1000), nullable=True),
    sa.Column('fraud_details', sa.String(length=1000), nullable=True),
    sa.Column('fraud_involved', sa.String(length=255), nullable=True),
    sa.Column('fraud_date', sa.String(length=100), nullable=True),
    sa.Column('discrimination_details', sa.String(length=1000), nullable=True),
    sa.Column('discrimination_basis', sa.String(length=255), nullable=True),
    sa.Column('safety_violation_details', sa.String(length=1000), nullable=True),
    sa.Column('safety_violation_date', sa.String(length=100), nullable=True),
    sa.Column('conflict_details', sa.String(length=1000), nullable=True),
    sa.Column('conflict_involved', sa.String(length=255), nullable=True),
    sa.Column('bribery_details', sa.String(length=1000), nullable=True),
    sa.Column('bribery_involved', sa.String(length=255), nullable=True),
    sa.Column('environment_violation_details', sa.String(length=1000), nullable=True),
    sa.Column('environment_violation_date', sa.String(length=100), nullable=True),
    sa.Column('mismanagement_details', sa.String(length=1000), nullable=True),
    sa.Column('mismanagement_responsible', sa.String(length=255), nullable=True),
    sa.Column('other_details', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
