name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up Miniconda
      uses: conda-inc/github-action@v2
      with:
        python-version: "3.10"
        auto-activate-base: false

    - name: Create Conda Environment
      run: |
        conda env create --file environment.yml --name myenv
        conda activate myenv

    - name: Cache Conda Environment
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Lint with flake8
      run: |
        conda run -n myenv flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n myenv flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda run -n myenv pytest
