name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: goanpeca/setup-miniconda@v1  # Correct version of the action
        with:
          python-version: 3.10
          activate-environment: myenv
          auto-activate-base: false
          environment-file: environment.yml

      - name: Cache Conda Packages
        uses: actions/cache@v3
        with:
          path: ~/.conda/envs
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Lint with flake8
        run: |
          conda run -n myenv flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          conda run -n myenv flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          conda run -n myenv pytest
