name: Python Package Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: "3.10"

    - name: Create Conda Environment
      run: |
        conda create --name myenv python=3.10 --yes
        conda activate myenv

    - name: Install Dependencies
      run: |
        conda install --name myenv flask flask-mail itsdangerous werkzeug --yes

    - name: Run Tests
      run: |
        conda activate myenv
        pytest
